### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by SanderZutt-CMD** [cmda-minor-vid/web-animation-19-20#1]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Sander Zutt`

## Class
`VID 2`

## About me
`Lange tijd niks met code gedaan, dus om eerlijk te zijn ben ik waarschijnlijk alles vergeten. Voornamelijk houd ik me bezig met vormgeving en het design van interfaces.`

## Goals
`Vrij obvious volgens mij maar het leren van animatie via HTML/CSS lijkt me erg handig. Animeren heb ik altijd al leuk gevonden, dus een andere manier van animeren leren is erg tof.`

## Skill level
`Intermediate: Gezien ik voornamelijk bezig ben geweest met vormgeving etc ben ik het coderen beetje vergeten, maar ik ga er stiekem van uit dat ik het snel weer op pak gezien dit ook lukte bij project WEB.`

## GitHub username
`https://github.com/SanderZutt-CMD`

## GitHub repository
`https://github.com/SanderZutt-CMD/SanderZutt-Web-Animation`

**Comment by dandevri** [comment]
🎉 Thanks Sander!
