### ISSUE TITLE
Introduction Robin Ansems 🐧

### ISSUE THREAD

**Issue by RobinAnsems** [cmda-minor-vid/web-animation-19-20#10]
# My Introduction

## Name
`Robin Ansems`

## Class
`VID 2`

## About me
`20 jaar uit Hilversum`

## Goals
`Mijn doel is om vette dingen te maken waar ik trots op ben!`

## Skill level
`intermediate`

## GitHub username
`RobinAnsems of https://github.com/RobinAnsems`

## GitHub repository
`https://robinansems.github.io/web-animation/`

**Comment by dandevri** [comment]
🎉 Thanks Robin!
