### ISSUE TITLE
Introduction Michael

### ISSUE THREAD

**Issue by IVIichael20** [cmda-minor-vid/web-animation-19-20#11]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Michael Varenhorst`

## Class
`VID 2`

## About me
`Komt uit Uithoorn, 20 jaar!`

## Goals
`Mijn horizon verbreden in de code.`

## Skill level
`Gemiddeld`

## GitHub username
`https://github.com/IVIichael20`

## GitHub repository
`https://github.com/IVIichael20/WebAnimatie`

**Comment by dandevri** [comment]
🎉 Thanks Michael!
