### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by jemiah** [cmda-minor-vid/web-animation-19-20#12]
# My Introduction

## Name
`Jemiah`

## Class
`VID1`

## About me
`I'm a student`

## Goals
`To learn more about CSS, HTML and Javascript`

## Skill level
`Beginner`

## GitHub username
`https://github.com/jemiah`

## GitHub repository
`https://github.com/jemiah/web-animatie.git`

**Comment by dandevri** [comment]
🎉 Thanks Jemiah!
