### ISSUE TITLE
Introduction Eva Veldt

### ISSUE THREAD

**Issue by Veldte** [cmda-minor-vid/web-animation-19-20#13]
# Introduction Eva Veldt

Ik ben Eva Veldt. Ik ben een CMD student en volg op dit moment de minor "Visual interface design". Tot nu toe was de minor erg tof, maar wie weet wordt het met deze twee vakken alleen nog maar beter! 

## Name
`Eva Veldt`

## Class
`VID 1`

## About me
`Ik ben een echte creatieveling en sta altijd open voor het leren van iets nieuws. Never try never know.`

## Goals
`Ik wil mijn skills verbeteren en kijken hoe ik toffe visuals in code kan vertalen. Ik denk dat ik met deze vakken weer nieuwe dingen ga leren.  Mijn doel is om er uit te halen wat er in zit en te kijken of ik echt iets gaafs neer kan zetten. `

## Skill level
`Ik denk dat ik over het algemeen intermediate ben. Wanneer het aankomt op HTML en CSS denk ik dat ik behoorlijk wat kan en dit ook voor een deel uit mijn hoofd kan.  JavaScript vind ik alleen een stuk lastiger maar ook daar begrijp ik wel altijd wat er staat. Om JavaScript uit mezelf te schrijven vind ik wel enorm lastig. Ik denk daarom dat intermediate wel mijn niveau is. `

## GitHub username
`https://github.com/Veldte`

## GitHub repository
`https://github.com/Veldte/EvaVeldtVID1`

##Link naar gekozen kunstwerk:
`https://designarchives.aiga.org/#/entries/Venture%20Graphics/_/detail/relevance/asc/0/7/12931/venture-graphics/1`

**Comment by dandevri** [comment]
🎉 Thanks Eva!
