### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Lisanneww** [cmda-minor-vid/web-animation-19-20#14]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Lisanne 

## Class
VID1

## About me
Hi, I'm a Media, Information and communication student so this is the first time I'll be coding something.

## Goals
I just want to learn the basics to be honest.

## Skill level
I think you could guess I'm a beginner.

## GitHub username
lisanneww

## GitHub repository
https://github.com/Lisanneww/Webanimation.git

**Comment by dandevri** [comment]
🎉 Thanks Lisanne!
