### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Kilian-Stuardo** [cmda-minor-vid/web-animation-19-20#15]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Kilian Stuardo

## Class
VID 1

## About me
i like video games, music and pizza.

## Goals
Beter worden in code en meer confident in code worden (code trauma) en er meer creatief mee kunnen denken

## Skill level
Beginner

## GitHub username
https://github.com/Kilian-Stuardo

## GitHub repository
https://github.com/Kilian-Stuardo/Web-Animatie

**Comment by dandevri** [comment]
🎉 Thanks Killian!
