### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by EmmaDeRuiter** [cmda-minor-vid/web-animation-19-20#16]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Emma de Ruiter`

## Class
`VID_1`

## About me
`Hey, ik ben Emma en ik ben niet zo goed in coderen.`

## Goals
`Lekker creatief bezig zijn en meer handigheid in html en css krijgen`

## Skill level
`Een beetje`

## GitHub Username
`https://github.com/EmmaDeRuiter`

## GitHub repository
`https://github.com/EmmaDeRuiter/webanimation.git`

**Comment by dandevri** [comment]
🎉 Thanks Emma!
