### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by lisaoosterom** [cmda-minor-vid/web-animation-19-20#17]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Lisa Oosterom

## Class
VID 2

## About me
Ik skeeler sinds corona elke dag 

## Goals
Zonder al te veel hoeven googlen of nadenken css kunnen schrijven

## Skill level
beginner, de basis lukt wel aardig, 

## GitHub username
https://github.com/lisaoosterom

## GitHub repository
https://github.com/lisaoosterom/htmlcss.git

**Comment by dandevri** [comment]
🎉 Thanks Lisa!
