### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by balouvaniterson** [cmda-minor-vid/web-animation-19-20#18]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Balou van Iterson`

## Class
`VID 1`

## About me
`I'm a student at the Hogeschool van Amsterdam`

## Goals
`Learn how to code`

## Skill level
`Beginner' (e.g. beginner, intermediate, advanced, geek)`

## GitHub username
`https://github.com/balouvaniterson`

## GitHub repository
`https://github.com/balouvaniterson/Minor`

**Comment by dandevri** [comment]
🎉 Thanks Balou!
