### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by DashingNass** [cmda-minor-vid/web-animation-19-20#19]
# My Introduction

Haii, nice to meet ya'll~.*

## Name
Nasséra Grampon

## Class
Visual Interface Design 2 – (VID 2)

## About me
I am (pretty) good at creating visual designs with programs like Photoshop, Sketch, InDesign and Illustrator. It's been a long time since I created something with coding, so I probably forgot the most stuff.

Currently I'm also creating a digital comic in my free time when I'm not working on school assignments 😄 
~~Might publish it online too if it's finished 😸  .~~

## Goals
~~My goals are world domination *laughs evil* lol, nah just kidding.~~
I am willing to know more about HTML and CSS since I'm always curious to try new things. 

- Learn more about HTML and CSS.
- Learn about CSS animations
- Maybe a little bit of JavaScript too(?)

But my ultimate goal is to understand this powerful (code) language more so I could create my own prototypes into a working product!

## Skill level
At HTML/CSS I would consider myself between a beginner and intermediate.
Since I don't code everyday it always brings me back to square one. 😅 
But... I do know how to read and write the code and can understand it a bit as well.

## GitHub username
https://github.com/DashingNass

## GitHub repository
https://github.com/DashingNass/web-animations

**Comment by dandevri** [comment]
🎉 Thanks Nasséra!
