### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by FlappyNarwal** [cmda-minor-vid/web-animation-19-20#2]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Isabel Mik

## Class
VID 1

## About me
I like cats.

## Goals
I want to learn how to create animations with code and become more familiar with code in general. Code kind of scares me.

## Skill level
Barely a beginner.

## GitHub username
https://github.com/FlappyNarwal

## GitHub repository
https://github.com/FlappyNarwal/WebAnimation

**Comment by dandevri** [comment]
🎉 Thanks Isabel!
