### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by joprodenhuis** [cmda-minor-vid/web-animation-19-20#20]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Jop Rodenhuis

## Class
VID1

## About me
Mijn naam is Jop Rodenhuis. Ik ben 20 jaar en ik woon in Leiden. Ik studeer CMD op de hogeschool van Den Haag en volg nu deze minor op de HvA. Ik heb vorig jaar stage gelopen bij een bedrijf wat zich richt op evenementen met bijbehorende event websites/apps. Mijn hobby's zijn sporten (korfbal) en video's bewerken. In de tijd die ik over heb drink ik graag een biertje met mijn vrienden.

## Goals
Ik zou graag voortgang willen maken in het animeren van web-interfaces op basis van input van de gebruikers.

## Skill level
Ik zou mijn ervaring omschrijven als gemiddeld. Ik heb genoeg ervaring met HTML, CSS en een beetje JavaScript. Hier heb ik ook tijdens mijn stage aan gewerkt. Wel is mijn kennis nog op basisniveau en zijn de website's die ik zelf kan programmeren nog erg statisch en kost het me vaak veel tijd.

## GitHub username
https://github.com/joprodenhuis

## GitHub repository
https://github.com/joprodenhuis/Web-animatie

**Comment by dandevri** [comment]
🎉 Thanks Jop!
