### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Shafiek31** [cmda-minor-vid/web-animation-19-20#21]
# My Introduction Shafiek

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Shafiek Ramzankhan`

## Class
`VID 2`

## About me
`Nieuwe perspectieven, daar ben ik bereid voor. Ik probeer altijd om mijn perspectief verder te verbreden.`

## Goals
`Meer weten over coderen, wellicht dat ik ook die kant op zou willen.`

## Skill level
`Beginner, ik weet wel wat leerstof maar het is nooit genoeg.`

## GitHub username
`https://github.com/Shafiek31`

## GitHub repository
`https://github.com/Shafiek31/minor-web-animatie`

## Eindopdracht - Link afbeelding
https://designarchives.aiga.org/#/entries/%2Bcollections%3A%22Denver%20Art%20Museum%22/_/detail/relevance/asc/4976/7/1707/light-years-poster/1

## Interacties eindopdracht
- Standaard: De letters gaan van boven naar onder en ook andersom EN/of alle kanten op.
- Buttons: Per woord een ander kleur. En/of Buttons per letter een ander kleur.
- Hoveren om de kleuren per letter naar voren te krijgen.
- Functie darkmode dat de achtergrond ineens dark is.

- Eventueel: op de letters klikken zodat die op de voorgrond blijven.

**Comment by dandevri** [comment]
🎉 Thanks Shafiek!

**Comment by Shafiek31** [comment]
Hoi Danny, 
Ik heb even een nieuwe link van de repository verwerkt in deze issue omdat de vorige link niet de css ging updaten. En zoals je kunt zien heb ik veel repository-mappen (ook van andere vakken) aangemaakt omdat ik niks begreep van github. Dus let daar aub niet op. De link die in deze issue staat is de link die je kunt beoordelen.
