### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by jorienkorn** [cmda-minor-vid/web-animation-19-20#22]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Jorien Korn

## Class
VID1

## About me
Luister veel naar muziek, verzamel CD's en band merch, hou van katten ook al heb ik er zelf geen

## Goals
Ik heb nog niet eerder geanimeerd met CSS dus ben benieuwd om dat te leren.

## Skill level
Beginner-intermediate, ik heb blok Web en FvD gedaan maar vind het nog altijd lastig.

## GitHub username
https://github.com/jorienkorn

## GitHub repository
https://github.com/jorienkorn/Web-Animation

**Comment by dandevri** [comment]
🎉 Thanks Jorien!
