### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by MartijnKeesmaat** [cmda-minor-vid/web-animation-19-20#23]
# My Introduction

## Name
Martijn Keesmaat 

## Class
VID2 

## About me
I have been trying to upload something each weekday on Dribbble. I have been doing this for about 5 weeks now. Recently I have been focusing on layout and typography, by experimenting with different grid systems like the golden ration and canon grid. I'm also trying to learn from a wider variety of sources like vintage newspapers, highlight reels, SWISS poster design, and graphic design history. Then I realize that I develop things and type out some code.

## Goals
Get introduced to processing, generative art, and physics.
P.S. how to make better work faster by working smarter

## Skill level
7/10

## GitHub username
[Me](https://github.com/MartijnKeesmaat)

## GitHub repository
[Repo](https://github.com/MartijnKeesmaat/web-animation)

**Comment by dandevri** [comment]
🎉 Thanks Martijn!
