### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by kimgarrard** [cmda-minor-vid/web-animation-19-20#24]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Kim Garrard

## Class
VID 2

## About me
`Write something about yourself`

## Goals
Beter leren animeren met CSS en nieuwe dingen leren. 

## Skill level
Intermediate

## GitHub username
kimgarrard

## GitHub repository
https://github.com/kimgarrard/magister

**Comment by dandevri** [comment]
🎉 Thanks Kim!
