### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Jussa23** [cmda-minor-vid/web-animation-19-20#25]
# My Introduction

## Name
Jesse Ros

## Class
VID1

## About me
Ik vind te veel dingen veel te leuk. Kan lastig zijn 🤔 
Maar mijn ontwerp interesses liggen vooral bij image editing, video editing en animeren.

## Goals
Ik hoop te leren om strakke animaties te kunnen maken en te begrijpen hoe je SVG's naar jou wil kunt manipuleren.

## Skill level
Intermediate. Ik heb verstand van basic HTML en CSS en vind het leuk om er af en toe mee te klooien.

## GitHub username
https://github.com/JesseJRos

## GitHub repository
https://github.com/JesseJRos/web-animation-19-20

**Comment by dandevri** [comment]
🎉 Thanks Jesse!
