### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by BasvandenBrink98** [cmda-minor-vid/web-animation-19-20#26]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Bas van den Brink`

## Class
`VID 1`

## About me
`Bij opdrachten die ik leuk vind ben ik erg perfectionistisch. Dit er soms voor zorgen dat ik in tijdnood kom, maar vaak zorgt het er voor dat het gene wat ik maak ook echt iets is waar ik trots op kan zijn. Verder speel ik vaak volleybal (nu wat minder helaas), en ben ik erg geïnteresseerd in graphic design en animatie.`

## Goals
`Mijn doel is om tijdens dit vak mijn kennis in animatie met css weer op te halen en verder te leren wat er mogelijk is. Daar bij wil ik svg animatie met css goed begrijpen en onder de knie krijgen. Zo ben ik met animatie niet alleen gebonden aan After Effects. `

## Skill level
`Mijn skill level is intermediate. De code gerelateerde vakken van CMD gingen mij best goed af. Ik heb alleen een tijdje niet meer met code gewerkt dus mijn kennis moet was opfrissen.`

## GitHub username
`https://github.com/BasvandenBrink98`

## GitHub repository
`https://github.com/BasvandenBrink98/Web-Animatie`

**Comment by dandevri** [comment]
🎉 Thanks Bas!
