### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by stellaniewenhuis** [cmda-minor-vid/web-animation-19-20#27]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Stella Niewenhuis`

## Class
`VID2`

## About me
`3de jaars student CMD`

## Goals
`Beter worden in coderen en programmeren`

## Skill level
`Beginner`

## GitHub username
`https://github.com/stellaniewenhuis`

## GitHub repository
`https://github.com/stellaniewenhuis/web-animation`

**Comment by dandevri** [comment]
🎉 Thanks Stella!
