### ISSUE TITLE
Introduction - Jamil

### ISSUE THREAD

**Issue by jamilvice** [cmda-minor-vid/web-animation-19-20#28]
# My Introduction Jamil

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Jamil Djabarkhan

## Class
VID2

## About me
A visual designer

## Goals
improve my css skills and combine it with my visual skills

## Skill level
beginner

## GitHub username
https://github.com/jamilvice

## GitHub repository
https://github.com/jamilvice/web-animatie

**Comment by dandevri** [comment]
🎉 Thanks Jamil!
