### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by MerelBracht** [cmda-minor-vid/web-animation-19-20#29]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Merel

## Class
VID1

## About me
Student Engineering Product Design

## Goals
HTML en CSS leren en onder de knie krijgen 

## Skill level
Beginner

## GitHub username
https://github.com/MerelBracht

## GitHub repository
https://github.com/MerelBracht?tab=repositories

**Comment by dandevri** [comment]
🎉 Thanks Merel!
