### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by demilouise** [cmda-minor-vid/web-animation-19-20#3]
# My Introduction

## Name
Demi Louise 

## Class
VID2

## About me
Ik kom van de opleiding Product Design en heb deze minor gekozen ter verbreding, maar eigenlijk als verdieping op me persoonlijke interesses naar vormgeving en ontwerpen. Ik ben verslaafd aan interieur design spullen kopen, sporten en ik mis uitgaan naar festivals. 

## Goals
Heel veel leren, onthouden en  geënthousiasmeerd worden. 

## Skill level
Absoluut beginner. 

## GitHub username
https://github.com/demilouise

## GitHub repository
https://github.com/demilouise/webanimatie

**Comment by dandevri** [comment]
🎉 Thanks Demi!
