### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by StephanKop** [cmda-minor-vid/web-animation-19-20#31]
# My Introduction

## Name
`Stephan Kop`

## Class
`VID 1`

## About me
`kind of a techie i guess?`

## Goals
`See how far you can go editing svg's`

## Skill level
`between intermediate and advanced`

## GitHub username
`superstephan1`

## GitHub repository
`https://github.com/superstephan1/web-animatie`

**Comment by dandevri** [comment]
🎉 Thanks Stephan!
