### ISSUE TITLE
Introduction Dorine

### ISSUE THREAD

**Issue by dorinereijersen** [cmda-minor-vid/web-animation-19-20#32]
# My Introduction

## Name
`Dorine Reijersen`

## Class
`VID1`

## About me
`Ik ben 20 jaar en ik houd er van om ergens mee bezig te zijn, stil zitten is niet mijn ding. In mn vrije tijd sport ik of aai ik mijn lieve katten.`

## Goals
`Dat ik een leuke animatie neerzet en dat ik trots wil zijn op mijn codeerwerk.`

## Skill level
`Ik denk dat ik een beginner ben die bijna intermediate is`

## GitHub username
`https://github.com/dorinereijersen`

## GitHub repository
`https://github.com/dorinereijersen/web-animatie`

**Comment by dandevri** [comment]
🎉 Thanks Dorine!
