### ISSUE TITLE
Introduction Renée

### ISSUE THREAD

**Issue by ReneeBuitendijk** [cmda-minor-vid/web-animation-19-20#33]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Renée Buitendijk

## Class
VID2

## About me
Cultureel Erfgoed student aan de Reinwardt Academie. Ik volg alleen deze minor.

## Goals
Ik heb nog nooit gecodeerd dus mijn doel voor dit blok is om te leren werken met CSS

## Skill level
Beginner

## GitHub username
`Add a link to your github page`

## GitHub repository
`Add a link to your github repository`

**Comment by dandevri** [comment]
🎉 Thanks Renee!
