### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by matsfeber** [cmda-minor-vid/web-animation-19-20#34]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Mats de Feber

## Class
VID 1

## About me
Ik ben 21 jaar en mijn interesses liggen bij ontwerpen en frontend. 
In mijn vrije tijd luister ik veel muziek, voornamelijk hip hop en deep grooves.
Daarnaast game ik ook, op dit moment speel ik overwatch en zelda the windwaker.
Bekijk mijn portfolio hier : https://matsfeber.myportfolio.com/ 

## Goals
Beter worden met Javascript en CSS, voornamelijk animaties maar ook responsive design.

## Skill level
Intermediate

## GitHub username
https://github.com/matsfeber

## GitHub repository
https://github.com/matsfeber/web_animation
https://matsfeber.github.io/web_animation/index.html

**Comment by dandevri** [comment]
🎉 Thanks Mats!
