### ISSUE TITLE
Introduction Maarten

### ISSUE THREAD

**Issue by MaartenBeek** [cmda-minor-vid/web-animation-19-20#35]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Maarten Beek`

## Class
`VID2`

## About me
`Write something about yourself`

## Goals
`What are your goals for this class?`

## Skill level
`intermediate`

## GitHub username
`Add a link to your github page`

## GitHub repository
`https://maartenbeek.github.io/web-animatie/`

**Comment by dandevri** [comment]
🎉 Thanks Maarten!
