### ISSUE TITLE
Introduction Lars

### ISSUE THREAD

**Issue by LarsCappelle** [cmda-minor-vid/web-animation-19-20#36]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Lars

## Class
`VID2`

## About me
`Mijn naam is Lars van de Cappelle. ik kom uit Amersfoort en ben 21 jaar. `

## Goals
`Ik wil graag leren wat de mogelijkheden zijn met het animeren van SVG's. Ook wil ik graag nieuwe, minder standaard, css animaties leren.`

## Skill level
`Intermediate op het gebied van HTML en CSS. Beginner op gebied van JS.`

## GitHub username
`https://github.com/LarsCappelle`

## GitHub repository
`https://github.com/LarsCappelle/WebAnimatieLars`

**Comment by dandevri** [comment]
🎉 Thanks Lars!
