### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Joelkenneth** [cmda-minor-vid/web-animation-19-20#37]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Joël Jansen

## Class
Minor VID 2

## About me
- Freelance Graphic Designer 
- The forever student
- Music Digger
- Gamer
- Surfing

## Goals
- Feeling confident using HTML/CSS/Javascript and finding the joy in it
- Passing this class with a complete desgin and without a stressful resit (too many times before)

## Skill level
Beginner

## GitHub username
Joelkenneth

## GitHub repository
https://github.com/Joelkenneth/web-animation-joel

**Comment by dandevri** [comment]
🎉 Thanks Joel!
