### ISSUE TITLE
Introduction Omar

### ISSUE THREAD

**Issue by SifuO5** [cmda-minor-vid/web-animation-19-20#38]
# My Introduction

## Name
Omar Fortgens

## Class
VID2

## About me
`Vormgeven, games, muziek maken, grappie op zn tijd`

## Goals
Websites ontwerpen die inspelen op de emotie van de gebruiker.

## Skill level
Intermediate

## GitHub username
`https://github.com/SifuO5`

## GitHub repository
`https://github.com/SifuO5/Web-animatie`

**Comment by dandevri** [comment]
Duplicate of #30
