### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by MissCage** [cmda-minor-vid/web-animation-19-20#4]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Tess van der Kooij

## Class
VID1

## About me
Ik kom van de opleiding Media, Informatie & Communicatie (Creative Business) en wil door middel van deze minor visueel sterker worden. Ik wil mijn skills verbeteren op het gebied van animeren, ontwerpen, creëren, coderen etc.

Ook speel ik graag Animal Crossing.

## Goals
Zelfstandig kunnen coderen, de basics. Iets creëren wat er in ieder geval semi oké uit ziet.

## Skill level
Heel erg beginner

## GitHub username
https://github.com/MissCage

## GitHub repository
https://github.com/MissCage/WebAnimation

**Comment by dandevri** [comment]
🎉 Thanks Tess!
