### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by NoelleLans** [cmda-minor-vid/web-animation-19-20#5]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Bart van der Lans

## Class
Vid2

## About me
I study informatica/computer science at the Hogeschool Leiden, but am now doing the Visual Interface Design minor in Amsterdam. 

## Goals
Learn something new.

## Skill level
I know a thing or 2 about html/css but not necessarily about web animation.

## GitHub username
https://github.com/bart211820

## GitHub repository
https://github.com/bart211820/web-animation

**Comment by dandevri** [comment]
🎉 Thanks Bart!
