### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by EmmaYounan** [cmda-minor-vid/web-animation-19-20#6]
# **My Introduction**

## Name 👩🏽
**Emma Younan**

## Class 👁
**VID 1**

## About me 🔦
A visual designer to be, with some development knowledge (mostly HTML and CSS and some basic JS). 

## Goals 🎯 
- Learn more about CSS grids.
- Learn more about how to use CSS animations. Instead of using gifs that slows down the website.

## Skill level 👩🏽‍🔬
Intermediate level (I can read, write, and understand almost all HTML and CSS.  I can read some JS and understand and write some of it).

## GitHub username 
[EmmaYounan](https://github.com/EmmaYounan)

## GitHub repository
https://github.com/EmmaYounan/Web-Animation

**Comment by dandevri** [comment]
🎉 Thanks Emma!
