### ISSUE TITLE
Introduction Rebecca

### ISSUE THREAD

**Issue by hutuber001** [cmda-minor-vid/web-animation-19-20#7]
# My Introduction

## Name
`Rebecca Hutubessy`

## Class
`VID2`

## About me
`I'm 21 and live in Hoofddorp.`

## Goals
`I would like to get more creative with html and css (and understand it better) so I could make my own design.`

## Skill level
`Between beginner and intermediate but iI think more towards the beginner.`

## GitHub username
`https://github.com/hutuber001/Web-animation`

## GitHub repository
`https://github.com/hutuber001/Web-animation.git`

**Comment by dandevri** [comment]
🎉 Thanks Rebecca!
