### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by ccdejene** [cmda-minor-vid/web-animation-19-20#8]
# My Introduction

## Name
`Eyob Westerink`

## Class
`VID1`

## About me
`Loving the web`

## Goals
`Broadening my knowledge in the web animation field`

## Skill level
`advanced`

## GitHub username
`eyobdejene`

## GitHub repository
`https://github.com/EyobDejene/web-animation`

**Comment by dandevri** [comment]
🎉 Thanks Eyob!
