### ISSUE TITLE
Introduction Romy👋🏼

### ISSUE THREAD

**Issue by rohmygod** [cmda-minor-vid/web-animation-19-20#9]
# My Introduction

## Name
`Romy Lenten`

## Class
`VID1`

## About me
`I'm 19, quite chaotic and I often speak before I think (so sorry in advance, 80% of the time I didn't mean to hurt you if I did). Always looking to make something you haven't seen yet.`

## Goals
`My goals for this class is to get better at writing html on my own and to be able to make animations. I often find myself understanding code when I read it and I'm able to tell you what kind of element you'll need for a page, yet when I have to write it in code by myself I just blank.`

## Skill level
`I'm not really sure, I guess intermediate. I know a little bit of everything and I'm able to set up a basic page with some javascript and such so.`

## GitHub username
`https://github.com/rohmygod`

## GitHub repository
`https://github.com/rohmygod/web-animation`

**Comment by dandevri** [comment]
🎉 Thanks Romy!
